### ISSUE TITLE
Rewrite Database Scripts to match our code styleguide

### ISSUE THREAD

**Issue by Eik-S** [tracemap/tracemap-backend#11]

**Comment by Eik-S** [comment]
Take a look at the [twitterApi.py](https://github.com/tracemap/tracemap-backend/blob/twitter-request-api-%234/api/twitter/twitterApi.py) script i wrote.
It should fit the style rules we defined [here](https://github.com/tracemap/tracemap-backend/tree/master/documents/styleguide) and you could take the structure as a base.
Start with creating a new branch containing the issue number at the end like "rewrite-database-scripts-#11".
Contact me for any help. :)

**Comment by brunopace** [comment]
### We need those functions:
- get_followers(user_ids: string[]): followers object
- add_user_info(user_info: object):true if user exists and success, false if user not exists or error
- get_user_info(user_id:string): user_info object

**Comment by brunopace** [comment]
We should discuss how the function add_user_info should behave:

- if it should take some extra time to check if the database is up-to-date and correctly wrote the requested info
- how should the returned value condense the information about the writing procedure
- if something goes wrong, where should this information be sent to, and which part of the system should handle that and occasionally retry to write the info to the database
- should the timestamp value only be updated once all these procedures guarantee that the write process was successful?
