### ISSUE TITLE
write flask api

### ISSUE THREAD

**Issue by Eik-S** [tracemap/tracemap-backend#5]

**Comment by Eik-S** [comment]
getRetweets( postId = "") #from twitterApi
```json
{ "response": [
    {"retweets": ["<userId>","<userId>"] }
  ]
}
```

getFollowers( userIds = []) #from neo4j
```json
{ "response": [
    {"<userId>":
      {"followers": ["<userId>","<userId>"] }
    },
    {"<userId>":
      {"followers": [] }
    }
  ]
}
```

getUserInfo( userId = "") #from neo4j or twitterApi
```json
{ "response": [
    {"<userId>": {
        "timestamp": 123,
        "name": "<userName>",
        "screen_name": "<screen_name",
        "location": "<location>",
        "followers_count": 123,
        "friends_count": 123,
        "statuses_count": 123,
        "created_at":"<timeString>",
        "profile_image_url": "<url>"
      }
    },
    {"<userId>": {
        "timestamp": 123,
        "name": "<userName>",
        "screen_name": "<screen_name",
        "location": "<location>",
        "followers_count": 123,
        "friends_count": 123,
        "statuses_count": 123,
        "created_at":"<timeString",
        "profile_image_url": "<url>"
      }
    }
  ]
}
```

**Comment by Eik-S** [comment]
## Folder Structure
  * **crawler**
  * **api**
    * **twitterRequest**
    * **serverRequest**
    * **tokenRequest**
    * flaskApi
  * **tests**

**Comment by Eik-S** [comment]
# Testing
 * Unit Tests
   * For every function
 * Functional Tests
   * For every feature

**Comment by Eik-S** [comment]
## Some useful resources:
 * https://blog.miguelgrinberg.com/post/designing-a-restful-api-with-python-and-flask

## API Authentication:
 * We can use the example from the tutorial above, using **flask_httpauth**s **HTTPBasicAuth**
 * For better security we should create a simple user database where a hashkey is created for a new user instead of allowing users to create their own password. this hashkey for the front-end is stored in environment variables.

**Comment by brunopace** [comment]
There is a line in your code like this: 

user_dict[ "profile_img_url"] = str(data['profile_image_url']) 

Is there a reason why you changed the property name? should we stick to the same convention Twitter uses not to get confused?
