### ISSUE TITLE
Solve docker problem.

### ISSUE THREAD

**Issue by Eik-S** [tracemap/tracemap-backend#59]

**Comment by jonathanschlue** [comment]
Assuming that this issue means the troubles @Eik-S and @jonathanschlue encounterd when rebuilding our API-Environment locally, we consider this problem fixed:

Packages `smtplib` and `email` were rebased into the python standard library, leaving the pipy versions unmaintained and incompatible with their dependencies,. Removing them from `requirements.txt` and thus forcing python to use the standard library versions fixed the issue.

See [the corresponding commit](https://github.com/tracemap/tracemap-backend/commit/14b0fed79144f03006284c1cf120c8442ed18bb0)
